version: '3'

services:
    api:
        platform: linux/amd64
        build: ./api/
        command: sh -c "sleep 5; npm run dev"
        restart: always
        links:
            - postgis
        ports:
            - "5000:5000"
        environment:
            - Postgres=postgres://docker:docker@postgis:5432/gis

    postgis:
        platform: linux/amd64
        image: kartoza/postgis:14.0
        restart: 'always'
        ports:
            - 5433:5432
        environment:
            - ALLOW_IP_RANGE=0.0.0.0/0
            - POSTGRES_DB=gis
            - POSTGRES_USER=docker
            - POSTGRES_PASS=docker
            - POSTGRES_MULTIPLE_EXTENSIONS="postgis","uuid-ossp"
