name: AWS ECR API

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.sha || github.sha}}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws-us-gov:iam::${{AWS_ACCOUNT_ID}}:role/Github-ECR-Builder
          role-session-name: GithubECRBuilder
          aws-region: ${{AWS_REGION}}

      - name: Docker Build API
        run: docker build -t api api/

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Docker Tag API
        run: docker tag api ${{secrets.AWS_ACCOUNT_ID}}.dkr.ecr.${{AWS_REGION}}.amazonaws.com/coe-ecr-stats:${{github.event.pull_request.head.sha || github.sha}}

      - name: Docker Push API
        run: docker push ${{secrets.AWS_ACCOUNT_ID}}.dkr.ecr.${{AWS_REGION}}.amazonaws.com/coe-ecr-stats:${{github.event.pull_request.head.sha || github.sha}}
